# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -U flake8 pytest
        
        # install this package (pulls dependencies from pyproject.toml)
        pip install -e .[yaml]
        
        # replace pip package with torch-sim from source (fairchem support)
        pip uninstall -y torch-sim-atomistic || true
        git clone https://github.com/TorchSim/torch-sim
        pip install ./torch-sim
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -q
